package com.example.jaby.service

enum class MainServiceActions {
    START_SERVICE,SETUP_VIEWS,STOP_SERVICE,START_WATCHING,END_STREAMING,
    SWITCH_CAMERA,TOGGLE_VIDEO,TOGGLE_AUDIO,TOGGLE_AUDIO_DEVICE
}